# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Album.create(title:'Glitterbox London', description:'After capturing the hearts of all who attended their summer residency at Space Ibiza over the last few months, the island’s most talked-about party, Glitterbox, now distils its unique, accessible and heritage-laden disco, soul and house soundtrack into this expansive release. Defected presents Glitterbox London is a new mix album from the most talked-about Ibiza party of recent memory, joining the dots between classic and contemporary dance music rooted in soul and disco and celebrating the rich and diverse dance music history of the UK’s capital.  Mixed by Defected’s founder Simon Dunmore and featuring some the most inspiring artists from the last 40 years of dance music, including Gwen Guthrie, First Choice, Patrice Rushen, Donald Byrd, Blondie, Breakbot, Moloko, and Purple Disco Machine, Glitterbox London is packed full of both unashamed anthems and hidden gems, and simply sparkles from start to finish. “Selecting tracks than span 30 years of my DJ career is hardly a chore” says Simon. “Digging through my vinyl and CDs, or even scrolling through my iTunes library, define specific moments of my involvement in the scene. I want the album to reflect all the elements that have influenced me...soul, jazz, funk, disco and house. The challenge is then to make it a cohesive musical journey for the listener.” “I believe the fact that Glitterbox has been reviewed so enthusiastically is down to the fact that the DJs curating the nights have real skills” says Simon. “They read the crowd and work to real moments in their sets. It is an art that is sadly declining, but it is clear from the reaction this summer how crucial understanding a room and your crowd is to achieving a great night. The album absolutely reflects the party. With both the focus is simply on great music.”', image_url:'albums/london.jpg', listen_url:'https://glitbx.lnk.to/ldn', cd_buy_url:'https://store.defected.com/defected-presents-glitterbox-london.html', cd_button_text:'Buy CD', vinyl_buy_url:'', vinyl_button_text:'')
Album.create(title:'Glitterbox For Your Disco Pleasure', description:'After lighting up Ibiza for 16 weeks straight at Space during the storied venue’s final season, Glitterbox returns with a new album, \'For Your Disco Pleasure\'. Compiled and mixed by Defected boss and Glitterbox founder Simon Dunmore, this two mix compilation epitomises exactly what to expect when you hit the dancefloor at these unique, spirit-lifting parties. Spanning 40 years of disco, boogie and house, ‘Glitterbox - For Your Disco Pleasure’ is bursting with feel-good music. Untouchable classics from the likes of Chic, Ashford & Simpson and the Larry Levan masterminded NYC Peech Boys harken back to dance music’s roots in glamorous discotheques, whilst productions from Masters At Work, Mousse T. and Henrik Schwarz are sure to evoke happy, hazy memories for house-heads. Soul Clap, Eli Escobar and DJ Koze point the way forward for electronic music rooted in funk and soul, and Lykke Li and Låpsley light the path for pop and dance music’s continuing symbiosis.', image_url:'albums/foryourdiscopleasure.jpg', listen_url:'https://glitbx.lnk.to/fydscplsr', cd_buy_url:'https://store.defected.com/glitterbox-for-your-disco-pleasure.html', cd_button_text:'Buy CD', vinyl_buy_url:'', vinyl_button_text:'')

Single.create(title:'Holding You Tight (Dr Packer Remixes)', artist:'Sure Thing', description:'Introducing the debut release on the brand new Glitterbox Recordings label; a label celebrating the incredible disco, nu disco, soul and classic house records that have made Glitterbox parties the most popular and joyous additions to the clubbing scene over the last few years. Sharing the Glitterbox nights’ philosophy for supporting artists who really know how to produce uplifting music that stays in your mind for days, Glitterbox’s first release is the much-anticipated Dr Packer remixes of Sure Thing’s the infectious nu disco classic ‘Holding You Tight’. Both Sure Thing and Dr Packer embody the Glitterbox ethos, making feel-good, joyful music that lights up the dancefloor. On the A side is the Dr Packer Remix and Instrumental while on the AA side is Sure Thing’s original Extended DJ Mix, alongside Dr Packer’s Radio Edit and Accapella, completing an essential landmark record to kick off your Glitterbox collection.', image_url:'singles/SureThing_HoldingYouTight_DrPackerRemixes.jpg', listen_url:'https://glitbx.lnk.to/sthytdrp', vinyl_buy_url:'', vinyl_button_text:'')
Single.create(title:'Glitterbox - For Your Disco Pleasure: Extended Player', artist:'Various Artists', description:'Providing a taste of what’s to come from the upcoming album Glitterbox – For Your Disco Pleasure, this sampler perfectly reflects the Glitterbox Recordings ethos; music with the sole purpose of getting you on the dancefloor. It also serves up a blend of old and new, with some brand new exclusive remixes and a lost classic from 4th Floor Records. First up is Purple Disco Machine & Boris Dlugosch’s 2016 hit ‘Set It Out’ remixed by Plaster Hands, a new collaborative project between Italian producers Tommy Vee, Mauro Ferrucci, Keller and Paolo Visnadi. The remix takes the summer smash down a couple of BPMs, maintaining the infectious melody but dropping the tempo in favour of a more laidback groove. Another brand new remix, David Morales’ version of Sonny Fodera’s ‘Feeling U’ featuring Yasmin lifts the track away from its deeper origins, giving it an irresistibly danceable classic house vibe and a glorious synth breakdown, while Yasmin’s gorgeous animated vocals further enhance the natural energy of the track. RIP Productions aka DJ Omar and Tim Deluxe are behind the third and final track on this Extended Player, with ‘She’s Got’. It’s a classic from 4th Floor Records vaults, featuring the quintessential driving 4/4 beat which sounds just as box fresh now as it did back in the day. It rounds off an EP of three outstanding tracks that will only leave you wanting more.', image_url:'singles/foryourdiscopleasure_ep.jpg', listen_url:'https://glitbx.lnk.to/frdpexnd', vinyl_buy_url:'', vinyl_button_text:'')

Person.create(name:'Basement Jaxx', bio:'First performing for Glitterbox in 2015, Simon Ratcliffe and Felix Buxton started life as underground producers and party promoters in 1995, putting out their first tracks on shrink-wrapped vinyl and throwing hush-hush raves in abandoned South London pizza joints. Almost a quarter of a century later, the double BRIT Award winners (Best Dance Act) have taken the sound of London to the world, also receiving a Grammy for their third album Kish Kash and continuing to produce quality releases on their own label, Atlantic Jaxx Recordings.', order:'1', image_url:'people/basementjaxx.jpg', facebook:'https://www.facebook.com/BasementJaxx', twitter:'http://twitter.com/TheBasementJaxx', instagram:'', soundcloud:'https://soundcloud.com/basement-jaxx', youtube:'http://www.youtube.com/officialbasementjaxx')
Person.create(name:'Masters At Work', bio:'There are few names in dance music today which need less of an introduction than Masters At Work. The duo of Louie Vega and Kenny Dope have forged a reputation for genre-eschewing DJ sets and flawless house productions during careers which have spanned three decades. Their sound was born out of New York when Disco was at its peak, seeing the emergence of house and hip-hop in their home city, the pair managed to amalgamate that mix along with a healthy dollop of Latin styles and jazz to create records that are still being copied and referenced – but crucially never eclipsed – by many of today’s contemporary producers.', order:'5', image_url:'people/maw,jpg', facebook:'https://www.facebook.com/MastersAtWorkOfficial/', twitter:'', instagram:'', soundcloud:'https://soundcloud.com/masters-at-work-official', youtube:'')
